<script type="text/javascript" src="/static/manage/admin/hui/lib/jquery/1.9.1/jquery.min.js"></script> 
<script type="text/javascript" src="/static/manage/admin/hui/lib/layer/2.1/layer.js"></script> 
<script type="text/javascript" src="/static/manage/admin/hui/lib/My97DatePicker/WdatePicker.js"></script> 
<script type="text/javascript" src="/static/manage/admin/hui/lib/jquery.validation/1.14.0/jquery.validate.min.js"></script> 
<script type="text/javascript" src="/static/manage/admin/hui/lib/jquery.validation/1.14.0/validate-methods.js"></script>
<script type="text/javascript" src="/static/manage/admin/hui/lib/jquery.validation/1.14.0/messages_zh.min.js"></script>  
<script type="text/javascript" src="/static/manage/admin/hui/static/h-ui/js/H-ui.js"></script> 
<script type="text/javascript" src="/static/manage/admin/hui/static/h-ui.admin/js/H-ui.admin.js"></script>
<script type="text/javascript" src="/static/manage/admin/hui/js/common.js"></script>
<script type="text/javascript" src="/static/manage/admin/hui/js/image.js"></script>
<script type="text/javascript" src="/static/manage/admin/uploadify/jquery.uploadify.min.js"></script>
